<?php

/**
 * @file
 * Contains timeout_notification.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function timeout_notification_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the timeout_notification module.
    case 'help.page.timeout_notification':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module will notify users of the drupal session expiring and allow them to refresh their session.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments_alter().
 *
 * @see https://www.drupal.org/node/2625300
 */
function timeout_notification_page_attachments_alter(array &$attachments) {
  // Check user authentication.
  if (\Drupal::currentUser()->isAuthenticated()) {
    // Get session expire settings.
    $max_lifetime = ini_get("session.gc_maxlifetime");
    // Get time till expire
    $config = \Drupal::config('timeout_notification.settings');
    $time_till_expire = $config->get('time_till_expire');
    // Create variables to check inside of timeout-notifier.js.
    $attachments['#attached']['drupalSettings']['timeout_notification']['timeout_notifier']['max_lifetime'] = $max_lifetime;
    $attachments['#attached']['drupalSettings']['timeout_notification']['timeout_notifier']['time_till_expire'] = $time_till_expire;
    // Include libraries.
    $attachments['#attached']['library'][] = 'timeout_notification/timeout-notifier';
  }
}
