# Schema file for the configuration files of the timeout notification module.
timeout_notification.settings:
  type: config_object
  label: 'Timeout Notification Settings'
  mapping:
    time_till_expire:
      type: integer
      label: 'Seconds Until Timeout to Notify User'
